apiVersion: apps/v1
kind: Deployment
metadata:
  name: devboard-be-deployment
  namespace: devboard
  labels:
    app: devboard-be #inside the deployment metadata, so this label is applied to the deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devboard-be #this is inside the deployment spec, so this  deployment can match pods with this label
  template:
    metadata:
      labels:
        app: devboard-be #this is inside the pod template, so this label is applied to the pod
    spec:
      containers:
        - name: devboard-be
          image: shivu212/backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: devboard-config
                  key: BACKEND_PORT
            - name: POSTGRES_URL
              # value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)?sslmode=disable     
                value: "postgres://devboard:$(POSTGRES_PASSWORD)@postgres:5432/devboard?sslmode=disable"