apiVersion: v1
kind: Pod
metadata:
  name: devboard-fe
  namespace: devboard
  labels:
    app: devboard-fe
spec:
  containers:
  - name: devboard-fe
    # Replace with your actual container registry and image tag
    image: shivu212/frontend:latest    
    ports:
    - containerPort: 80
