apiVersion: apps/v1
kind: Deployment
metadata:
  name: devboard-be-depl
  namespace: devboard
  labels:
    app: devboard-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devboard-be
  template:
    metadata:
      labels:
        app: devboard-be
    spec:
      containers:
      - name: devboard-be
        image: shivu212/backend:latest
        ports:
        - containerPort: 8080

